[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
SERVICE_PROTOCOL = "rest"
SERVICE_HOST = "0.0.0.0"
XRAY_EXECUTABLE_PATH = "/usr/local/bin/xray"
XRAY_ASSETS_PATH = "/usr/local/share/xray"
SSL_DIR = "/var/lib/marzban-node"
